export enum StatoPartitaEnum {
  HOME = "HOME",
  INIZIALIZZAZIONE_GIOCATORI = "INIZIALIZZAZIONE_GIOCATORI",
  PARTITA_IN_CORSO = "PARTITA_IN_CORSO",
  PARTITA_CONCLUSA = "PARTITA_CONCLUSA",
  PUNTEGGI_PARTITE_PRECEDENTI = "PUNTEGGI_PARTITE_PRECEDENTI",
}
